### PR TITLE
Update rehype-code-titles to take in options

### PR DESCRIPTION
**Pull request by tearingItUp786**
## Description

[Issue link](https://github.com/rockchalkwushock/rehype-code-titles/issues/237)

Introduce the ability to pass in optional arguments to the `rehype-code-titles` plugin. Must maintain backward compatibility. 😊

### CODE REVIEW

**Comment by rockchalkwushock** [comment]
@tearingItUp786 

Apparently I never included the `preinstall` script to prevent usage of `npm` or `yarn` to install since the repo uses `pnpm`.  And that is what is causing the CI to fail right now. Can you please do the following:

1. Remove `package-lock.json`
2. Add `"preinstall": "npx only-allow pnpm" to the `package.json` scripts.
3. Please change the entry for the new dependency to read `"hast": "~1.0.0"` for patch updates only
4. Run `pnpm install` and commit the updated `pnpm-lock.yaml`

Everything with the code and updated tests look great. Thank you for updating the documentation as well! 🙏🏻

**Comment by tearingItUp786** [comment]
@rockchalkwushock done!

**Comment by rockchalkwushock** [comment]
@tearingItUp786 Looks like there are some TS errors.

**Comment by tearingItUp786** [comment]
@rockchalkwushock had to update some of the dependencies and introduce a new dev dependency; hopefully, that's okay!

**Comment by rockchalkwushock** [comment]
@tearingItUp786 looks great thanks for submitting the PR and fixing up those TS bugs. I will merge to staging and if not later this evening then tomorrow morning will push to production and release the new version to NPM. Thanks again 🎉

**Pull request merged**
